name = "alife-cloudflare-api"
main = "worker/index.js"
compatibility_date = "2026-04-17"
workers_dev = true

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "ccalc"
preview_bucket_name = "ccalc"

[vars]
R2_BUCKET_NAME = "ccalc"
R2_PUBLIC_BASE_URL = "https://images.ccalc.live"
BUCKET_LIST_LIMIT = "500"